Loading LIBD module for git-status-size/github
Loading LIBD module for git-lfs/2.8.0
Loading LIBD module for rmate/1.5.9
Loading LIBD module for ruby/2.6.4p104
Loading conda_R/devel
**** Job starts ****
Mon Jan  2 07:02:39 EST 2023
**** JHPCE info ****
User: sparthib
Job id: 1382748
Job name: magma_heatmap
Hostname: compute-098.cm.cluster
Task id: 2
Unloading conda_R/devel
Loading conda_R/4.2

The following have been reloaded with a version change:
  1) conda/3-4.6.14 => conda/3-4.11.0     2) conda_R/devel => conda_R/4.2


Currently Loaded Modules:
  1) matlab/R2019a     6) COMMUNITY_CENTOS7_DEFAULT_ENV  11) ruby/2.6.4p104
  2) stata/17          7) JHPCE_CENTOS7_DEFAULT_ENV      12) rmate/1.5.9
  3) JHPCE_tools/1.0   8) git-status-size/github         13) conda/3-4.11.0
  4) sge/8.1.9         9) git/2.28.0                     14) conda_R/4.2
  5) gcc/4.4.7        10) git-lfs/2.8.0

 

here() starts at /dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[1] "/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD"
Error in paste0("ad_gwas_", gene_set[SGE_TASK_ID], ".gsa.out") : 
  object 'SGE_TASK_ID' not found
Calls: read.table -> here -> <Anonymous> -> path -> paste0
Execution halted
**** Job ends ****
Mon Jan  2 07:02:49 EST 2023
Loading LIBD module for git-status-size/github
Loading LIBD module for git-lfs/2.8.0
Loading LIBD module for rmate/1.5.9
Loading LIBD module for ruby/2.6.4p104
Loading conda_R/devel
**** Job starts ****
Mon Jan  2 07:16:39 EST 2023
**** JHPCE info ****
User: sparthib
Job id: 1382749
Job name: magma_heatmap
Hostname: compute-098.cm.cluster
Task id: 2
Unloading conda_R/devel
Loading conda_R/4.2

The following have been reloaded with a version change:
  1) conda/3-4.6.14 => conda/3-4.11.0     2) conda_R/devel => conda_R/4.2


Currently Loaded Modules:
  1) matlab/R2019a     6) COMMUNITY_CENTOS7_DEFAULT_ENV  11) ruby/2.6.4p104
  2) stata/17          7) JHPCE_CENTOS7_DEFAULT_ENV      12) rmate/1.5.9
  3) JHPCE_tools/1.0   8) git-status-size/github         13) conda/3-4.11.0
  4) sge/8.1.9         9) git/2.28.0                     14) conda_R/4.2
  5) gcc/4.4.7        10) git-lfs/2.8.0

 

here() starts at /dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[1] "/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD"
Using Region, Pathology_Type as id variables
[1] 21  4
Using Region, Pathology_Type as id variables

TRUE 
  21 
  Region Pathology_Type           GWAS      Beta        P P.adj.fdr
1    ITC             Ab AD.Jansen.2019  0.041632 0.289260 0.5522236
2    ITC           both AD.Jansen.2019 -0.042155 0.696740 0.8314845
3    ITC        next_Ab AD.Jansen.2019 -0.134540 0.950070 0.9500700
4    ITC      next_both AD.Jansen.2019  0.043430 0.288460 0.5522236
5    ITC        next_pT AD.Jansen.2019 -0.040185 0.691490 0.8314845
6    ITC           none AD.Jansen.2019  0.171060 0.014898 0.1564290
Warning message:
In dir.create(here("plots", "magma")) :
  '/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD/plots/magma' already exists
Error in paste0("heatmap_", "top_", gene_num[k], "_genes", ".pdf") : 
  object 'gene_num' not found
Calls: pdf ... gsub -> is.factor -> here -> <Anonymous> -> path -> paste0
Execution halted
**** Job ends ****
Mon Jan  2 07:16:44 EST 2023
Loading LIBD module for git-status-size/github
Loading LIBD module for git-lfs/2.8.0
Loading LIBD module for rmate/1.5.9
Loading LIBD module for ruby/2.6.4p104
Loading conda_R/devel
**** Job starts ****
Mon Jan  2 07:20:24 EST 2023
**** JHPCE info ****
User: sparthib
Job id: 1382750
Job name: magma_heatmap
Hostname: compute-098.cm.cluster
Task id: 2
Unloading conda_R/devel
Loading conda_R/4.2

The following have been reloaded with a version change:
  1) conda/3-4.6.14 => conda/3-4.11.0     2) conda_R/devel => conda_R/4.2


Currently Loaded Modules:
  1) matlab/R2019a     6) COMMUNITY_CENTOS7_DEFAULT_ENV  11) ruby/2.6.4p104
  2) stata/17          7) JHPCE_CENTOS7_DEFAULT_ENV      12) rmate/1.5.9
  3) JHPCE_tools/1.0   8) git-status-size/github         13) conda/3-4.11.0
  4) sge/8.1.9         9) git/2.28.0                     14) conda_R/4.2
  5) gcc/4.4.7        10) git-lfs/2.8.0

 

here() starts at /dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[1] "/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD"
Using Region, Pathology_Type as id variables
[1] 21  4
Using Region, Pathology_Type as id variables

TRUE 
  21 
  Region Pathology_Type           GWAS      Beta        P P.adj.fdr
1    ITC             Ab AD.Jansen.2019  0.041632 0.289260 0.5522236
2    ITC           both AD.Jansen.2019 -0.042155 0.696740 0.8314845
3    ITC        next_Ab AD.Jansen.2019 -0.134540 0.950070 0.9500700
4    ITC      next_both AD.Jansen.2019  0.043430 0.288460 0.5522236
5    ITC        next_pT AD.Jansen.2019 -0.040185 0.691490 0.8314845
6    ITC           none AD.Jansen.2019  0.171060 0.014898 0.1564290
Warning message:
In dir.create(here("plots", "magma")) :
  '/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD/plots/magma' already exists
Error in pdf(here("plots", "magma", paste0("heatmap_", "top_", gene_set[k],  : 
  cannot open file '/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD/plots/magma/heatmap_top_100_genes.pdf/6'
In addition: Warning message:
Arguments must be unnamed 
Execution halted
**** Job ends ****
Mon Jan  2 07:20:29 EST 2023
Loading LIBD module for git-status-size/github
Loading LIBD module for git-lfs/2.8.0
Loading LIBD module for rmate/1.5.9
Loading LIBD module for ruby/2.6.4p104
Loading conda_R/devel
**** Job starts ****
Mon Jan  2 07:29:18 EST 2023
**** JHPCE info ****
User: sparthib
Job id: 1382753
Job name: magma_heatmap
Hostname: compute-095.cm.cluster
Task id: 2
Unloading conda_R/devel
Loading conda_R/4.2

The following have been reloaded with a version change:
  1) conda/3-4.6.14 => conda/3-4.11.0     2) conda_R/devel => conda_R/4.2


Currently Loaded Modules:
  1) matlab/R2019a     6) COMMUNITY_CENTOS7_DEFAULT_ENV  11) ruby/2.6.4p104
  2) stata/17          7) JHPCE_CENTOS7_DEFAULT_ENV      12) rmate/1.5.9
  3) JHPCE_tools/1.0   8) git-status-size/github         13) conda/3-4.11.0
  4) sge/8.1.9         9) git/2.28.0                     14) conda_R/4.2
  5) gcc/4.4.7        10) git-lfs/2.8.0

 

here() starts at /dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[1] "/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD"
[1] 2
[1] "100"
Using Region, Pathology_Type as id variables
[1] 21  4
Using Region, Pathology_Type as id variables

TRUE 
  21 
Error in path("/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD",  : 
  argument is missing, with no default
Calls: write.csv ... eval -> eval -> <Anonymous> -> here -> <Anonymous> -> path
Execution halted
**** Job ends ****
Mon Jan  2 07:29:23 EST 2023
Loading LIBD module for git-status-size/github
Loading LIBD module for git-lfs/2.8.0
Loading LIBD module for rmate/1.5.9
Loading LIBD module for ruby/2.6.4p104
Loading conda_R/devel
**** Job starts ****
Mon Jan  2 07:32:02 EST 2023
**** JHPCE info ****
User: sparthib
Job id: 1382754
Job name: magma_heatmap
Hostname: compute-098.cm.cluster
Task id: 2
Unloading conda_R/devel
Loading conda_R/4.2

The following have been reloaded with a version change:
  1) conda/3-4.6.14 => conda/3-4.11.0     2) conda_R/devel => conda_R/4.2


Currently Loaded Modules:
  1) matlab/R2019a     6) COMMUNITY_CENTOS7_DEFAULT_ENV  11) ruby/2.6.4p104
  2) stata/17          7) JHPCE_CENTOS7_DEFAULT_ENV      12) rmate/1.5.9
  3) JHPCE_tools/1.0   8) git-status-size/github         13) conda/3-4.11.0
  4) sge/8.1.9         9) git/2.28.0                     14) conda_R/4.2
  5) gcc/4.4.7        10) git-lfs/2.8.0

 

here() starts at /dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[1] "/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD"
[1] 2
[1] "100"
Using Region, Pathology_Type as id variables
[1] 21  4
Using Region, Pathology_Type as id variables

TRUE 
  21 
  Region Pathology_Type           GWAS      Beta        P P.adj.fdr
1    ITC             Ab AD.Jansen.2019  0.041632 0.289260 0.5522236
2    ITC           both AD.Jansen.2019 -0.042155 0.696740 0.8314845
3    ITC        next_Ab AD.Jansen.2019 -0.134540 0.950070 0.9500700
4    ITC      next_both AD.Jansen.2019  0.043430 0.288460 0.5522236
5    ITC        next_pT AD.Jansen.2019 -0.040185 0.691490 0.8314845
6    ITC           none AD.Jansen.2019  0.171060 0.014898 0.1564290
Warning message:
In dir.create(here("plots", "magma")) :
  '/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD/plots/magma' already exists
Error in pdf(here("plots", "magma", paste0("heatmap_", "top_", gene_set[k],  : 
  cannot open file '/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD/plots/magma/heatmap_top_100_genes.pdf/6'
In addition: Warning message:
Arguments must be unnamed 
Execution halted
**** Job ends ****
Mon Jan  2 07:32:07 EST 2023
Loading LIBD module for git-status-size/github
Loading LIBD module for git-lfs/2.8.0
Loading LIBD module for rmate/1.5.9
Loading LIBD module for ruby/2.6.4p104
Loading conda_R/devel
**** Job starts ****
Mon Jan  2 07:34:20 EST 2023
**** JHPCE info ****
User: sparthib
Job id: 1382755
Job name: magma_heatmap
Hostname: compute-095.cm.cluster
Task id: 2
Unloading conda_R/devel
Loading conda_R/4.2

The following have been reloaded with a version change:
  1) conda/3-4.6.14 => conda/3-4.11.0     2) conda_R/devel => conda_R/4.2


Currently Loaded Modules:
  1) matlab/R2019a     6) COMMUNITY_CENTOS7_DEFAULT_ENV  11) ruby/2.6.4p104
  2) stata/17          7) JHPCE_CENTOS7_DEFAULT_ENV      12) rmate/1.5.9
  3) JHPCE_tools/1.0   8) git-status-size/github         13) conda/3-4.11.0
  4) sge/8.1.9         9) git/2.28.0                     14) conda_R/4.2
  5) gcc/4.4.7        10) git-lfs/2.8.0

 

here() starts at /dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[1] "/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD"
[1] 2
[1] "100"
Using Region, Pathology_Type as id variables
[1] 21  4
Using Region, Pathology_Type as id variables

TRUE 
  21 
  Region Pathology_Type           GWAS      Beta        P P.adj.fdr
1    ITC             Ab AD.Jansen.2019  0.041632 0.289260 0.5522236
2    ITC           both AD.Jansen.2019 -0.042155 0.696740 0.8314845
3    ITC        next_Ab AD.Jansen.2019 -0.134540 0.950070 0.9500700
4    ITC      next_both AD.Jansen.2019  0.043430 0.288460 0.5522236
5    ITC        next_pT AD.Jansen.2019 -0.040185 0.691490 0.8314845
6    ITC           none AD.Jansen.2019  0.171060 0.014898 0.1564290
Warning message:
In dir.create(here("plots", "magma")) :
  '/dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD/plots/magma' already exists
Error in image.plot(x = seq(0, ncol(wide_p), by = 1), y = clusterHeights,  : 
  could not find function "image.plot"
Calls: MAGMAplot
Execution halted
**** Job ends ****
Mon Jan  2 07:34:30 EST 2023
